# Site settings
author: Paloma Mendez
title: Popkorn's Coding 
header-img: img/home-bg.png
email: mpaloma2014@gmail.com
copyright_name: Paloma Mendez
description: > # this means to ignore newlines until "baseurl:"
  Beginning coder loving the challenge!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  popkorn96

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
